### ISSUE TITLE
It cannot find the release folder, when it s already made

### ISSUE THREAD

**Issue by kh3zyyy** [joaoviictorti/shadow-rs#2]
error:
![Screenshot 2024-08-14 135235](https://github.com/user-attachments/assets/66f6d0ac-dcac-4347-bece-61c8c71eb273)
 [cargo-make] INFO - cargo make 0.37.15
[cargo-make] INFO - Execute Command: "rust-script" "target\\_cargo_make_temp\\persisted_scripts\\D4060E7434B3779E78A683E8BA00D06A5D08BE8C95BC432359E22F06CB30EF1C.rs"
[cargo-make] INFO - Calling cargo metadata to extract project info
[cargo-make] INFO - Cargo metadata done
[cargo-make] INFO - Project: shadow
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: default
[cargo-make] INFO - Profile: development
[cargo-make] ERROR - Error while running plugin: Source: Unknown Line: 38 - [tasks.wdk-build-init]'s script failed with exit code: 1
stdout:
FORWARDING ARGS TO CARGO-MAKE:
CARGO_MAKE_CARGO_PROFILE=release
CARGO_MAKE_CARGO_BUILD_TEST_FLAGS=--release
WDK_BUILD_OUTPUT_DIRECTORY=C:\Users\kh3zyy\Downloads\shadow-rs-main\shadow-rs-main\driver\target/release

stderr:
Error: IoError(Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." })

The temporary rust-script file is located at C:\Users\kh3zyy\Downloads\shadow-rs-main\shadow-rs-main\driver\target/cargo-make-script/wdk-build-init/main.rs
[cargo-make] WARN - Build Failed.

**Comment by joaoviictorti** [comment]
Possibly the error occurred because you changed the name of the project to `shadow-rs-main`. The Makefile used by Microsoft expects the `.inx` file to have the same name as the project (which in this case I put shadow), otherwise the file won't be found.

**Comment by joaoviictorti** [comment]
If you have any other questions, you can reopen this issue.

**Comment by kh3zyyy** [comment]
Hey, new error popped up. i changed the directory name and installed latest windows SDK

**error code**: 
```rust
error: failed to run custom build command for `wdk-sys v0.2.0`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `C:\Users\kh3zyy\Downloads\shadow-rs-main (1)\shadow\driver\target\release\build\wdk-sys-7ece108ea6b6c7ff\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=TARGET
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS
  cargo:rerun-if-changed=src/ntddk-input.h
  cargo:rerun-if-changed=src/wdf-input.h

  --- stderr
  thread 'main' panicked at C:\Users\kh3zyy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bindgen-0.69.4\lib.rs:622:31:
  Unable to find libclang: "couldn't find any valid shared libraries matching: ['clang.dll', 'libclang.dll'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"
  stack backtrace:
     0:     0x7ff622b94e94 - std::backtrace_rs::backtrace::dbghelp64::trace
                                 at /rustc/13a52890dde8cfeb95069d77c223ac37c0cf3a46\library/std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:91
     1:     0x7ff622b94e94 - std::backtrace_rs::backtrace::trace_unsynchronized
                                 at /rustc/13a52890dde8cfeb95069d77c223ac37c0cf3a46\library/std\src\..\..\backtrace\src\backtrace\mod.rs:66
     2:     0x7ff622b94e94 - std::sys::backtrace::_print_fmt
                                 at /rustc/13a52890dde8cfeb95069d77c223ac37c0cf3a46\library/std\src\sys\backtrace.rs:66
     3:     0x7ff622b94e94 - std::sys::backtrace::impl$0::print::impl$0::fmt
                                 at /rustc/13a52890dde8cfeb95069d77c223ac37c0cf3a46\library/std\src\sys\backtrace.rs:39
     4:     0x7ff622bb5779 - core::fmt::rt::Argument::fmt
                                 at /rustc/13a52890dde8cfeb95069d77c223ac37c0cf3a46\library/core\src\fmt\rt.rs:173
     5:     0x7ff622bb5779 - core::fmt::write
                                 at /rustc/13a52890dde8cfeb95069d77c223ac37c0cf3a46\library/core\src\fmt\mod.rs:1178
     6:     0x7ff622b8ff57 - std::io::Write::write_fmt<std::sys::pal::windows::stdio::Stderr>
                                 at /rustc/13a52890dde8cfeb95069d77c223ac37c0cf3a46\library/std\src\io\mod.rs:1823
     7:     0x7ff622b96fa9 - std::panicking::default_hook::closure$1
                                 at /rustc/13a52890dde8cfeb95069d77c223ac37c0cf3a46\library/std\src\panicking.rs:266
     8:     0x7ff622b96b2c - std::panicking::default_hook
                                 at /rustc/13a52890dde8cfeb95069d77c223ac37c0cf3a46\library/std\src\panicking.rs:293
     9:     0x7ff622b978b2 - std::panicking::rust_panic_with_hook
                                 at /rustc/13a52890dde8cfeb95069d77c223ac37c0cf3a46\library/std\src\panicking.rs:797
    10:     0x7ff622b976f6 - std::panicking::begin_panic_handler::closure$0
                                 at /rustc/13a52890dde8cfeb95069d77c223ac37c0cf3a46\library/std\src\panicking.rs:671
    11:     0x7ff622b9594f - std::sys::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                                 at /rustc/13a52890dde8cfeb95069d77c223ac37c0cf3a46\library/std\src\sys\backtrace.rs:170    12:     0x7ff622b97306 - std::panicking::begin_panic_handler
                                 at /rustc/13a52890dde8cfeb95069d77c223ac37c0cf3a46\library/std\src\panicking.rs:662
    13:     0x7ff622bbf4f4 - core::panicking::panic_fmt
                                 at /rustc/13a52890dde8cfeb95069d77c223ac37c0cf3a46\library/core\src\panicking.rs:74
    14:     0x7ff622bbf910 - core::result::unwrap_failed
                                 at /rustc/13a52890dde8cfeb95069d77c223ac37c0cf3a46\library/core\src\result.rs:1679
    15:     0x7ff6226f05a4 - core::result::Result<T,E>::expect::h00f4e38ee356ae2e
    16:     0x7ff6226e558c - core::ops::function::FnOnce::call_once::hbd7701dc50e0ed59
    17:     0x7ff6227f976b - lazy_static::lazy::Lazy<T>::get::{{closure}}::hb125b0997715dfb6
    18:     0x7ff622766f90 - std::sync::once::Once::call_once::{{closure}}::h180da9a7b6d3c283
    19:     0x7ff622bbe6e4 - std::sys::sync::once::futex::Once::call
                                 at /rustc/13a52890dde8cfeb95069d77c223ac37c0cf3a46\library/std\src\sys\sync\once\futex.rs:168
    20:     0x7ff622766e2d - std::sync::once::Once::call_once::hb1198c6396e4a4d3
    21:     0x7ff62270df6a - <bindgen::ensure_libclang_is_loaded::LIBCLANG as core::ops::deref::Deref>::deref::h38fd88f82ccccab0
    22:     0x7ff622707929 - bindgen::deprecated_target_diagnostic::h1350aff37d269ca0
    23:     0x7ff6227085ee - bindgen::deprecated_target_diagnostic::h1350aff37d269ca0
    24:     0x7ff6227070fd - bindgen::Builder::generate::h4d3a72ff6897386a
    25:     0x7ff6225b8f1d - <core::option::IntoIter<A> as core::iter::traits::iterator::Iterator>::next::h6c2273fcab33ff8d
    26:     0x7ff6225ba6e4 - <core::option::IntoIter<A> as core::iter::traits::iterator::Iterator>::next::h6c2273fcab33ff8d
    27:     0x7ff6225bddd6 - core::ops::function::FnOnce::call_once::hb1c897a7fa362a3c
    28:     0x7ff6225b7179 - std::rt::lang_start::{{closure}}::h670d257352476b87
    29:     0x7ff6225b714c - std::rt::lang_start::{{closure}}::h670d257352476b87
    30:     0x7ff622b8a519 - std::rt::lang_start_internal::closure$2
                                 at /rustc/13a52890dde8cfeb95069d77c223ac37c0cf3a46\library/std\src\rt.rs:143
    31:     0x7ff622b8a519 - std::panicking::try::do_call
                                 at /rustc/13a52890dde8cfeb95069d77c223ac37c0cf3a46\library/std\src\panicking.rs:554
    32:     0x7ff622b8a519 - std::panicking::try
                                 at /rustc/13a52890dde8cfeb95069d77c223ac37c0cf3a46\library/std\src\panicking.rs:518
    33:     0x7ff622b8a519 - std::panic::catch_unwind
                                 at /rustc/13a52890dde8cfeb95069d77c223ac37c0cf3a46\library/std\src\panic.rs:345
    34:     0x7ff622b8a519 - std::rt::lang_start_internal
                                 at /rustc/13a52890dde8cfeb95069d77c223ac37c0cf3a46\library/std\src\rt.rs:143
    35:     0x7ff6225b7127 - std::rt::lang_start::hb338e2eea3afbeba
    36:     0x7ff6225bb379 - main
    37:     0x7ff622bbc7f0 - invoke_main
                                 at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    38:     0x7ff622bbc7f0 - __scrt_common_main_seh
                                 at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    39:     0x7ffc699e7374 - BaseThreadInitThunk
    40:     0x7ffc6af1cc91 - RtlUserThreadStart
Error while executing command, exit code: 101
```

**Comment by joaoviictorti** [comment]
Try these installations that Microsoft recommends before building the driver: https://github.com/microsoft/windows-drivers-rs?tab=readme-ov-file#getting-started

**Comment by kh3zyyy** [comment]
worked 👍
